GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content" : "POSTING second noteusing mongoose to MongoDB.",
    "important" : false
}